### PR TITLE
fix: iOS swipe input recursion

### PR DESCRIPTION
**Pull request by NuVeS**
Fixed recursion on ios13 swipe text input

### CODE REVIEW

**Comment by taflanidi** [comment]
So, you are saying pasting the same string from the clipboard is now prohibited? (-:

**Comment by NuVeS** [comment]
you're right. Instead of checking last input, it's better to check if the input change current text. And if not - then it's recursion we want to avoid

**Comment by taflanidi** [comment]
Well, in #81 I mentioned a more radical solution to remove both `MaskedTextFieldDelegate` and `MaskedTextViewDelegate` altogether, in favour of `MaskedTextInputListener`. 

I'd like to avoid adding unnecessary workarounds.

**Comment by taflanidi** [comment]
Closing this and #81 due to inactivity.

**Pull request closed without merging**
